name: "Build Android app"

on:
  
  push:
    branches:
      - master
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 11
          distribution: adopt
          cache: gradle
          
      - name: Setup Node  
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '12.14.1'
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.5.0
        with:
          # Exact version to use
          ndk-version: r21e
          # Add installation directory to the PATH
          add-to-path: true
          # Add installed NDK to the Android SDK
          link-to-sdk: true
          # Use the local job cache on top of the runner tool cache
          local-cache: false
      - name: Run npm Install
        working-directory: ./app-client
        run: |
             
             npm install -g corepack
             npm install --save
             npm install react-native --save
             npm install -g react-native-cli --force

      - name: Build application
        working-directory: ./app-client
        run: |
             cd android
             ./gradlew assembleDebug
      - name: Upload application
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
